name: Android (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'


    - name: Get Submodules
      run: ./get_dlc

    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile shader
      working-directory: shader
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile texture
      working-directory: texture
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile computeshader
      working-directory: computeshader
      run: ../kore/make android -g vulkan --debug --compile
    - name: Compile texturearray
      working-directory: texturearray
      run: ../kore/make android -g vulkan --debug --compile
