name: iOS (OpenGL)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4


    - name: Get Submodules
      run: ./get_dlc

