name: Linux (OpenGL)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libwayland-dev wayland-protocols libxkbcommon-dev ninja-build imagemagick xvfb --yes --quiet

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run 00_empty
      working-directory: 00_empty/deployment
      run: xvfb-run ../build/debug/00_empty
    - name: Check 00_empty
      working-directory: 00_empty
      run: node ../.github/compare.js
    - name: Upload 00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/deployment/test.png
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run 01_triangle
      working-directory: 01_triangle/deployment
      run: xvfb-run ../build/debug/01_triangle
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: node ../.github/compare.js
    - name: Upload 01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/deployment/test.png
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run 02_matrix
      working-directory: 02_matrix/deployment
      run: xvfb-run ../build/debug/02_matrix
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: node ../.github/compare.js
    - name: Upload 02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/deployment/test.png
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run 03_colored_cube
      working-directory: 03_colored_cube/deployment
      run: xvfb-run ../build/debug/03_colored_cube
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: node ../.github/compare.js
    - name: Upload 03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/deployment/test.png
    - name: Compile shader
      working-directory: shader
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run shader
      working-directory: shader/deployment
      run: xvfb-run ../build/debug/shader
    - name: Check shader
      working-directory: shader
      run: node ../.github/compare.js
    - name: Upload shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/deployment/test.png
