name: Linux (Vulkan)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get LunarG key
      run: wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
    - name: Get LunarG apt sources
      run: sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev vulkan-sdk libwayland-dev wayland-protocols libxkbcommon-dev ninja-build --yes --quiet

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 00_empty
      working-directory: 00_empty/deployment
      run: xvfb-run ../build/debug/00_empty
    - name: Check 00_empty
      working-directory: 00_empty
      run: compare-im6 -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload 00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/Deployment/test.png
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 01_triangle
      working-directory: 01_triangle/deployment
      run: xvfb-run ../build/debug/01_triangle
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: compare-im6 -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload 01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/Deployment/test.png
    - name: Compile shader
      working-directory: shader
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run shader
      working-directory: shader/deployment
      run: xvfb-run ../build/debug/shader
    - name: Check shader
      working-directory: shader
      run: compare-im6 -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
