name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get LunarG key
      run: wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
    - name: Get LunarG apt sources
      run: sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev vulkan-sdk mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers libwayland-dev wayland-protocols libxkbcommon-dev ninja-build imagemagick xvfb --yes --quiet

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 00_empty
      working-directory: 00_empty/deployment
      run: xvfb-run ../build/debug/00_empty
    - name: Check 00_empty
      working-directory: 00_empty
      run: node ../.github/compare.js
    - name: Upload 00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/deployment/test.png
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 01_triangle
      working-directory: 01_triangle/deployment
      run: xvfb-run ../build/debug/01_triangle
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: node ../.github/compare.js
    - name: Upload 01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/deployment/test.png
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 02_matrix
      working-directory: 02_matrix/deployment
      run: xvfb-run ../build/debug/02_matrix
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: node ../.github/compare.js
    - name: Upload 02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/deployment/test.png
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 03_colored_cube
      working-directory: 03_colored_cube/deployment
      run: xvfb-run ../build/debug/03_colored_cube
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: node ../.github/compare.js
    - name: Upload 03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/deployment/test.png
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 04_textured_cube
      working-directory: 04_textured_cube/deployment
      run: xvfb-run ../build/debug/04_textured_cube
    - name: Check 04_textured_cube
      working-directory: 04_textured_cube
      run: node ../.github/compare.js
    - name: Upload 04_textured_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 04_textured_cube image
        path: 04_textured_cube/deployment/test.png
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 05_camera_controls
      working-directory: 05_camera_controls/deployment
      run: xvfb-run ../build/debug/05_camera_controls
    - name: Check 05_camera_controls
      working-directory: 05_camera_controls
      run: node ../.github/compare.js
    - name: Upload 05_camera_controls failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 05_camera_controls image
        path: 05_camera_controls/deployment/test.png
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 06_render_targets
      working-directory: 06_render_targets/deployment
      run: xvfb-run ../build/debug/06_render_targets
    - name: Check 06_render_targets
      working-directory: 06_render_targets
      run: node ../.github/compare.js
    - name: Upload 06_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 06_render_targets image
        path: 06_render_targets/deployment/test.png
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 07_multiple_render_targets
      working-directory: 07_multiple_render_targets/deployment
      run: xvfb-run ../build/debug/07_multiple_render_targets
    - name: Check 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: node ../.github/compare.js
    - name: Upload 07_multiple_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 07_multiple_render_targets image
        path: 07_multiple_render_targets/deployment/test.png
    - name: Compile 08_float_render_targets
      working-directory: 08_float_render_targets
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 08_float_render_targets
      working-directory: 08_float_render_targets/deployment
      run: xvfb-run ../build/debug/08_float_render_targets
    - name: Check 08_float_render_targets
      working-directory: 08_float_render_targets
      run: node ../.github/compare.js
    - name: Upload 08_float_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 08_float_render_targets image
        path: 08_float_render_targets/deployment/test.png
    - name: Compile 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 09_depth_render_targets
      working-directory: 09_depth_render_targets/deployment
      run: xvfb-run ../build/debug/09_depth_render_targets
    - name: Check 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: node ../.github/compare.js
    - name: Upload 09_depth_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 09_depth_render_targets image
        path: 09_depth_render_targets/deployment/test.png
    - name: Compile 10_cubemap
      working-directory: 10_cubemap
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 10_cubemap
      working-directory: 10_cubemap/deployment
      run: xvfb-run ../build/debug/10_cubemap
    - name: Check 10_cubemap
      working-directory: 10_cubemap
      run: node ../.github/compare.js
    - name: Upload 10_cubemap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 10_cubemap image
        path: 10_cubemap/deployment/test.png
    - name: Compile 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 12_set_render_target_depth
      working-directory: 12_set_render_target_depth/deployment
      run: xvfb-run ../build/debug/12_set_render_target_depth
    - name: Check 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: node ../.github/compare.js
    - name: Upload 12_set_render_target_depth failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 12_set_render_target_depth image
        path: 12_set_render_target_depth/deployment/test.png
    - name: Compile 14_set_mipmap
      working-directory: 14_set_mipmap
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run 14_set_mipmap
      working-directory: 14_set_mipmap/deployment
      run: xvfb-run ../build/debug/14_set_mipmap
    - name: Check 14_set_mipmap
      working-directory: 14_set_mipmap
      run: node ../.github/compare.js
    - name: Upload 14_set_mipmap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 14_set_mipmap image
        path: 14_set_mipmap/deployment/test.png
    - name: Compile shader
      working-directory: shader
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run shader
      working-directory: shader/deployment
      run: xvfb-run ../build/debug/shader
    - name: Check shader
      working-directory: shader
      run: node ../.github/compare.js
    - name: Upload shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/deployment/test.png
    - name: Compile texture
      working-directory: texture
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run texture
      working-directory: texture/deployment
      run: xvfb-run ../build/debug/texture
    - name: Check texture
      working-directory: texture
      run: node ../.github/compare.js
    - name: Upload texture failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texture image
        path: texture/deployment/test.png
    - name: Compile computeshader
      working-directory: computeshader
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run computeshader
      working-directory: computeshader/deployment
      run: xvfb-run ../build/debug/computeshader
    - name: Check computeshader
      working-directory: computeshader
      run: node ../.github/compare.js
    - name: Upload computeshader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: computeshader image
        path: computeshader/deployment/test.png
    - name: Compile texturearray
      working-directory: texturearray
      run: ../kore/make linux -g vulkan --debug --option screenshot --compile
    - name: Run texturearray
      working-directory: texturearray/deployment
      run: xvfb-run ../build/debug/texturearray
    - name: Check texturearray
      working-directory: texturearray
      run: node ../.github/compare.js
    - name: Upload texturearray failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texturearray image
        path: texturearray/deployment/test.png
