name: macOS (Metal)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4


    - name: Get Submodules
      run: ./get_dlc

    - name: Compile shader
      working-directory: shader
      run: ../Kore/make osx -g metal --option screenshot --debug --run
    - name: Check shader
      working-directory: shader
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
