name: Windows (Vulkan)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("--da", "--al", "-c", "in");
          $installer.WaitForExit();
    - name: Get Submodules
      run: ./get_dlc

    - name: Compile shader
      working-directory: shader
      run: ../kore/make windows -v vs2022 -g vulkan --debug --option screenshot --run
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Check shader
      working-directory: shader
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
