name: Windows (OpenGL)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4


    - name: Get Submodules
      run: ./get_dlc

    - name: Compile shader
      working-directory: shader
      run: ../kore/make windows -v vs2022 -g opengl --debug --compile
