name: Windows (Direct3D 12)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install WARP 1.0.13
      run: nuget install Microsoft.Direct3D.WARP -Version 1.0.13
    - name: Get Submodules
      run: ./get_dlc

    - name: Copy WARP
      working-directory: 00_empty
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 00_empty
      working-directory: 00_empty
      run: node ../.github/compare.js
    - name: Upload 00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/deployment/test.png
    - name: Copy WARP
      working-directory: 01_triangle
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: node ../.github/compare.js
    - name: Upload 01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/deployment/test.png
    - name: Copy WARP
      working-directory: 02_matrix
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: node ../.github/compare.js
    - name: Upload 02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/deployment/test.png
    - name: Copy WARP
      working-directory: 03_colored_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: node ../.github/compare.js
    - name: Upload 03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/deployment/test.png
    - name: Copy WARP
      working-directory: 04_textured_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 04_textured_cube
      working-directory: 04_textured_cube
      run: node ../.github/compare.js
    - name: Upload 04_textured_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 04_textured_cube image
        path: 04_textured_cube/deployment/test.png
    - name: Copy WARP
      working-directory: 05_camera_controls
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 05_camera_controls
      working-directory: 05_camera_controls
      run: node ../.github/compare.js
    - name: Upload 05_camera_controls failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 05_camera_controls image
        path: 05_camera_controls/deployment/test.png
    - name: Copy WARP
      working-directory: 06_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 06_render_targets
      working-directory: 06_render_targets
      run: node ../.github/compare.js
    - name: Upload 06_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 06_render_targets image
        path: 06_render_targets/deployment/test.png
    - name: Copy WARP
      working-directory: 07_multiple_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: node ../.github/compare.js
    - name: Upload 07_multiple_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 07_multiple_render_targets image
        path: 07_multiple_render_targets/deployment/test.png
    - name: Copy WARP
      working-directory: 08_float_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 08_float_render_targets
      working-directory: 08_float_render_targets
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 08_float_render_targets
      working-directory: 08_float_render_targets
      run: node ../.github/compare.js
    - name: Upload 08_float_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 08_float_render_targets image
        path: 08_float_render_targets/deployment/test.png
    - name: Copy WARP
      working-directory: 09_depth_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: node ../.github/compare.js
    - name: Upload 09_depth_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 09_depth_render_targets image
        path: 09_depth_render_targets/deployment/test.png
    - name: Copy WARP
      working-directory: 10_cubemap
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 10_cubemap
      working-directory: 10_cubemap
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 10_cubemap
      working-directory: 10_cubemap
      run: node ../.github/compare.js
    - name: Upload 10_cubemap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 10_cubemap image
        path: 10_cubemap/deployment/test.png
    - name: Copy WARP
      working-directory: 11_instanced_rendering
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: node ../.github/compare.js
    - name: Upload 11_instanced_rendering failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 11_instanced_rendering image
        path: 11_instanced_rendering/deployment/test.png
    - name: Copy WARP
      working-directory: 12_set_render_target_depth
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: node ../.github/compare.js
    - name: Upload 12_set_render_target_depth failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 12_set_render_target_depth image
        path: 12_set_render_target_depth/deployment/test.png
    - name: Copy WARP
      working-directory: 13_generate_mipmaps
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: node ../.github/compare.js
    - name: Upload 13_generate_mipmaps failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 13_generate_mipmaps image
        path: 13_generate_mipmaps/deployment/test.png
    - name: Copy WARP
      working-directory: 14_set_mipmap
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 14_set_mipmap
      working-directory: 14_set_mipmap
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 14_set_mipmap
      working-directory: 14_set_mipmap
      run: node ../.github/compare.js
    - name: Upload 14_set_mipmap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 14_set_mipmap image
        path: 14_set_mipmap/deployment/test.png
    - name: Copy WARP
      working-directory: 15_deinterleaved_buffers
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: node ../.github/compare.js
    - name: Upload 15_deinterleaved_buffers failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 15_deinterleaved_buffers image
        path: 15_deinterleaved_buffers/deployment/test.png
    - name: Copy WARP
      working-directory: shader
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile shader
      working-directory: shader
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check shader
      working-directory: shader
      run: node ../.github/compare.js
    - name: Upload shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/deployment/test.png
    - name: Copy WARP
      working-directory: texture
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile texture
      working-directory: texture
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check texture
      working-directory: texture
      run: node ../.github/compare.js
    - name: Upload texture failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texture image
        path: texture/deployment/test.png
    - name: Copy WARP
      working-directory: computeshader
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile computeshader
      working-directory: computeshader
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check computeshader
      working-directory: computeshader
      run: node ../.github/compare.js
    - name: Upload computeshader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: computeshader image
        path: computeshader/deployment/test.png
    - name: Copy WARP
      working-directory: texturearray
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile texturearray
      working-directory: texturearray
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check texturearray
      working-directory: texturearray
      run: node ../.github/compare.js
    - name: Upload texturearray failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texturearray image
        path: texturearray/deployment/test.png
    - name: Copy WARP
      working-directory: raytracing
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile raytracing
      working-directory: raytracing
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check raytracing
      working-directory: raytracing
      run: node ../.github/compare.js
    - name: Upload raytracing failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: raytracing image
        path: raytracing/deployment/test.png
    - name: Copy WARP
      working-directory: bindless
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile bindless
      working-directory: bindless
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check bindless
      working-directory: bindless
      run: node ../.github/compare.js
    - name: Upload bindless failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: bindless image
        path: bindless/deployment/test.png
    - name: Copy WARP
      working-directory: busybuffers
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile busybuffers
      working-directory: busybuffers
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check busybuffers
      working-directory: busybuffers
      run: node ../.github/compare.js
    - name: Upload busybuffers failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: busybuffers image
        path: busybuffers/deployment/test.png
    - name: Copy WARP
      working-directory: busydescriptors
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll deployment\d3d10warp.dll
    - name: Compile busydescriptors
      working-directory: busydescriptors
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check busydescriptors
      working-directory: busydescriptors
      run: node ../.github/compare.js
    - name: Upload busydescriptors failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: busydescriptors image
        path: busydescriptors/deployment/test.png
