name: Windows (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("--da", "--al", "-c", "in");
          $installer.WaitForExit();
    - name: Get Submodules
      run: ./get_dlc

    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile shader
      working-directory: shader
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile texture
      working-directory: texture
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile computeshader
      working-directory: computeshader
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
    - name: Compile texturearray
      working-directory: texturearray
      run: ../kore/make windows -v vs2022 -g vulkan --debug --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
